### ISSUE TITLE
make install error : in function emu_env_w32_new #3

### ISSUE THREAD

**Issue by ghost** [buffer/libemu#3]
I am using OS X and i git clone the latest version however i got the same error.

environment/win32/emu_env_w32.c:395:17: error: unused typedef 'PLIST_ENTRY' [-Werror,-Wunused-local-typedef]
        } LIST_ENTRY, _PLIST_ENTRY; //, *RESTRICTED_POINTER PRLIST_ENTRY;
                       ^
environment/win32/emu_env_w32.c:418:27: error: unused typedef 'PLDR_DATA_TABLE_ENTRY' [-Werror,-Wunused-local-typedef]
        } LDR_DATA_TABLE_ENTRY, *PLDR_DATA_TABLE_ENTRY;
                                 ^
environment/win32/emu_env_w32.c:398:24: error: unused typedef 'BYTE' [-Werror,-Wunused-local-typedef]
        typedef unsigned char BYTE;
                              ^
environment/win32/emu_env_w32.c:385:21: error: unused typedef 'PUNICODE_STRING' [-Werror,-Wunused-local-typedef]
        } UNICODE_STRING, *PUNICODE_STRING;
                           ^
environment/win32/emu_env_w32.c:431:4: error: unused typedef 'PEB_LDR_DATA' [-Werror,-Wunused-local-typedef]
        } PEB_LDR_DATA, *PPEB_LDR_DATA;
          ^
environment/win32/emu_env_w32.c:418:4: error: unused typedef 'LDR_DATA_TABLE_ENTRY' [-Werror,-Wunused-local-typedef]
        } LDR_DATA_TABLE_ENTRY, *PLDR_DATA_TABLE_ENTRY;
          ^
environment/win32/emu_env_w32.c:431:19: error: unused typedef 'PPEB_LDR_DATA' [-Werror,-Wunused-local-typedef]
        } PEB_LDR_DATA, *PPEB_LDR_DATA;
                         ^
7 errors generated.
make[2]: *_\* [environment/win32/emu_env_w32.lo] Error 1
make[1]: **\* [install-recursive] Error 1
make: **\* [install-recursive] Error 1

**Comment by buffer** [comment]
In theory the last patch I submitted should solve the issue but I don't know which version of gcc you are currently using. Moreover I don't have a OSX here to make additional tests so please provide further details so that I can blindly figure out what's going on. Thanks.

**Comment by WindyOrgUK** [comment]
Hello,

I just run into exactly the same issue when trying to make.
Running Mac OS X El Capitan.
GCC version:

gcc --version

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-
dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

# 

What else can be useful to tshoot this ?
and btw, thanks a lot for your work.

Regards
Peter

**Comment by buffer** [comment]
Unfortunately I do not have access to any Mac OS X host so I am currently unable to properly troubleshoot the issue. Can you try removing the option -Wunused-local-typedef and see it it stops the compilation error occurence?

**Comment by suifeng9** [comment]
Excuse me.
I have the same issue, and how to removing the option -Wunused-local-typedef?
my gcc version is gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 and I just clone your latest version! Thank you!

**Comment by buffer** [comment]
The commit 72f073ca32090d42558e44f7bf9b5cfce0438fd5 should have already solved the issue. Can you try running a 'pip install pylibemu'? It will install libemu and the Python bindings as well. I maintain pylibemu and its setup script should take care of a few details even related to libemu.

**Comment by suifeng9** [comment]
Thank you! I have installed libemu and pylibemu successfully, maybe I downloaded the wrong version 1.0 before.

**Comment by codekraft-studio** [comment]
@buffer I tried to do run `pip install pylibemu` but it failed with this error message:

```
Package libemu was not found in the pkg-config search path.
Perhaps you should add the directory containing `libemu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libemu' found
Traceback (most recent call last):
...
```

so I tried to install directly libemu and it worked apparently but when I run again: pip install pylibemu I get the same error No package 'libemu' found.

Also (for my linux version opensuse) I had to do this command `autoreconf -v -i` before `./configure` because the configure file was missing, I read it from [here](http://blog.xanda.org/2012/05/16/installation-of-libemu-and-pylibemu-on-ubuntu/) maybe you can modify the readme to add this case.

I would like to try **thug** but it fails on installing pylibemu :sob:, I have nearly finished installing it I miss only this error I guess!

Many thanks in advance!

**Comment by buffer** [comment]
In theory the newest pylibemu should be able to take care of all these details. I was able to install it through pip both on Linux and Mac OS X. FYI the commands you point out are executed by setup when you install through pip. One thing you could try is running 

`export PKG_CONFIG_PATH = "$PKG_CONFIG_PATH":$(locate libemu.pc)`

and then install through pip. Let me know.

**Comment by codekraft-studio** [comment]
ok it worked like a charm and I've also finished to install **thug** but when I run: `thug -h` (to check if is working) it stops on importing pylibemu:

```
import pylibemu
ImportError: libemu.so.2: cannot open shared object file: No such file or directory
```

What shoul I do to test if pylibemu is installed correctly?

**Comment by buffer** [comment]
Please run (as root)

echo "/opt/libemu/lib/" > /etc/ld.so.conf.d/libemu.conf && ldconfig

**Comment by codekraft-studio** [comment]
**great**! is working and i'm about to test it in the next days! Many thanks!
