### ISSUE TITLE
please use release system

### ISSUE THREAD

**Issue by shibumi** [buffer/libemu#4]
Hello,
I want to package this package for the Arch Linux User Repository it would be awesome if you could use the release system of github. 

best regards

chris

**Comment by buffer** [comment]
Well you should be aware I am not the libemu maintainer. I have just contributed to it from time to time and patched a compilation issue recently. Do you think it would make sense?

**Comment by shibumi** [comment]
@buffer 
Yes I think it would make sense. Your github project is the current main project of libemu. 
So please create a release version for libemu..

btw http://libemu.mwcollect.org/ looks down.

**Comment by buffer** [comment]
Done! Published release v1.0

https://github.com/buffer/libemu/releases/tag/v1.0

**Comment by q2dg** [comment]
Well, it seems this project is pretty abandoned, anyway

**Comment by buffer** [comment]
Why are you assuming this project is abandoned? Having neither new features to implement nor issues to solve does not mean a project is abandoned. If you are experiencing issues or you're interested in a new feature feel free to open a Github issue. Otherwise please avoid useless comments. Thanks.

**Comment by q2dg** [comment]
Well, you could begin changing the url to (inexistent) homepage in your readme.

**Comment by buffer** [comment]
This is not a project I developed in the first place but I just forked it. And I'm not going to remove the original references even if they do not exist anymore. If you can live with a wrong url in a readme file you're welcome to use this fork. If you can't feel free to fork the project and do these essential changes by yourself.
