### ISSUE TITLE
make install error: "PAGE_SIZE" redefined [-Werror]

### ISSUE THREAD

**Issue by standa4** [buffer/libemu#5]
Hello,
during the compilation of libemu on alpine linux 3.4 I am getting following error:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -D _GNU_SOURCE -I/usr/local/include -Wno-unused-local-typedefs -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -pipe -D _GNU_SOURCE -I../include -Werror -Wall -g -g -O2 -Wstrict-prototypes -MT emu_memory.lo -MD -MP -MF .deps/emu_memory.Tpo -c emu_memory.c  -fPIC -DPIC -o .libs/emu_memory.o
emu_memory.c:44:0: error: "PAGE_SIZE" redefined [-Werror]
 #define PAGE_SIZE (1 << PAGE_BITS)
 ^
In file included from /usr/include/limits.h:8:0,
                 from /usr/include/fortify/stdlib.h:25,
                 from emu_memory.c:29:
/usr/include/bits/limits.h:3:0: note: this is the location of the previous definition
 #define PAGE_SIZE 4096
 ^
cc1: all warnings being treated as errors
Makefile:785: recipe for target 'emu_memory.lo' failed
make[3]: *** [emu_memory.lo] Error 1
make[3]: Leaving directory '/tmp/libemu/src'
Makefile:809: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/libemu/src'
Makefile:460: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/libemu'
Makefile:369: recipe for target 'all' failed
make: *** [all] Error 2

Thank you.

**Comment by buffer** [comment]
Can you try applying this simple patch? (I can not do it by myself right now but if it works I will include in the master tree as soon as possible)

The file to modify is src/emu_memory.c. You should replace the following line (line 44)

`#define PAGE_SIZE (1 << PAGE_BITS)`

with these 3 lines 

```
#ifndef PAGE_SIZE
  #define PAGE_SIZE (1 << PAGE_BITS)
#endif
```

and recompile.

If you don't feel comfortable in doing it I will take care of it as soon as I can.

**Comment by standa4** [comment]
Thank you for your response. 
With this patch it compiles without any issues.
